package com.user.entity;


import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "user_role_department")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserRoleDepartment {

    @EmbeddedId
    private UserRoleDepartmentKey id;  // Composite Key

    // Constructors to initialize the composite key
    public UserRoleDepartment(String userId, int roleId, int departmentId) {
        this.id = new UserRoleDepartmentKey(userId, roleId, departmentId);
    }

    // Getters and Setters (can be generated by Lombok)
    public UserRoleDepartmentKey getId() {
        return id;
    }

    public void setId(UserRoleDepartmentKey id) {
        this.id = id;
    }
}


